bug: application crash

This test has run with --dataParTasksPerLocale=1 since it was added.
It even had an assert(dataParTasksPerLocale==1).

Removing that option and that assert, the test crashes with:

m-lsms.par-forall.chpl:67: error: halt reached - array index out of bounds: (1)

where in a single multilocale run I have seen three errors with the erroneous
indices of 1, 6, and 9.

Briefly looking at the code, I did not even see any array indexing operations
there, and did not investigate further. Valgrind did not turn up anything,
and the program runs successfully under valgrind. It is unclear to me
whether it is an application code bug or a Chapel bug.

Serializing that particular forall, the code runs successfully.
So I am putting a 'serial serialForall do' around it where serialForall
default to 'true' and is 'false' for this .future.

Once this bug is fixed, this future should be removed altogether
and 'serialForall' and the 'serial' statement be removed from
the main code.
